[CI] Change docker user to ec2-user (#2834)
Add back in an explicitly defined user in the docker build because I can't figure out which user is being used by the docker image.  If a user other than ec2-user is being used, then it is not possibly for the next job to clean up files from previous jobs because it lacks permission.

Should fix the problems like https://github.com/pytorch/tutorials/actions/runs/8635938916/job/23674817847
```

Cleaning the repository
Warning: Unable to clean or reset the repository. The repository will be recreated instead.
Deleting the contents of '/home/ec2-user/actions-runner/_work/tutorials/tutorials'
Error: File was unable to be removed Error: EACCES: permission denied, unlink '/home/ec2-user/actions-runner/_work/tutorials/tutorials/.jenkins/__pycache__/get_files_to_run.cpython-310.pyc'
```