Pin docutils to 0.16
docutils-0.17 causes sphinx-build to fail with:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 69: ordinal not in range(128)
```
Which comes from new https://sourceforge.net/p/docutils/code/8590/tree/trunk/docutils/docutils/writers/latex2e/docutils.sty